site_name: あかたか赤高

nav:
  - 首页: index.md
  - 保送: page1.md
  - 双学位: page2.md
  - 资源: page3.md

theme:
  name: material
  language: zh
  palette:
    primary: cyan
    
  features:
    - navigation.tabs


