# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.cache/wt [current_project]
set_property parent.project_path C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/DHT11.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/clk_div_1.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/clothing_advice.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/display.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/main.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/pin.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/select.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/str_display.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/temp_to_digits.v
  C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/sources_1/new/clothes_system.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/constrs_1/new/clothes_system.xdc
set_property used_in_implementation false [get_files C:/Users/Bricksburg-Akataka/Desktop/浙江大学/课程文件/数字系统/clothes_system/clothes_system/clothes_system.srcs/constrs_1/new/clothes_system.xdc]


synth_design -top clothes_system -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef clothes_system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file clothes_system_utilization_synth.rpt -pb clothes_system_utilization_synth.pb"
